name: trailerness
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - h5py
  - hydra-core=1.3.2
  - jupyter
  - numpy=1.24.4
  - opencv=4.7.0
  - pandas=2.0.3
  - pip
  - pillow=10.0.0
  - python=3.8
  - pytorch-cuda=11.7
  - pytorch=2.0.0
  - pytorch-lightning=2.0.6
  - seaborn=0.12.2
  - torchvision=0.15.2
  - torchmetrics=0.11.4
  - torchaudio=2.0.0
  - wandb=0.15.8